#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use SebaCarrasco93\Kaataa\Console\Commands\CreateCommand;
use SebaCarrasco93\Kaataa\Console\Commands\MakeTestCommand;
use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new CreateCommand());
$application->add(new MakeTestCommand());

$application->run();
